owner: danielphan2003
repo: unlasting

sites:
  - name: Vaultwarden (User)
    url: https://vault.pik2.duckdns.org

  - name: Vaultwarden (Admin)
    url: https://pik2.penguin-major.ts.net/vault/admin

  - name: Grafana
    url: https://pik2.penguin-major.ts.net/grafana

commitMessages:
  commitAuthorName: "GitHub automation"
  commitAuthorEmail: "danielphan.2003@gmail.com"
